### ISSUE TITLE
spelling mistake for LamdbaExceptionUtils

### ISSUE THREAD

**Issue by cuidd2018** [BluSpring/Kilt#12]
[https://github.com/KiltMC/Kilt/blob/1.20.1/src/main/java/cpw/mods/modlauncher/api/LamdbaExceptionUtils.java](url)

**Comment by BluSpring** [comment]
Funny thing, this actually is an intentional spelling mistake.

In the 1.20.1 and prior builds of Forge, LambdaExceptionUtils is actually, genuinely named LamdbaExceptionUtils.
[I wish I was joking](https://github.com/McModLauncher/modlauncher/commits/main/src/main/java/cpw/mods/modlauncher/api/LambdaExceptionUtils.java).
